server:
  port: "@server.port@"
  servlet:
    contextPath: "@context.path@"

spring:
  datasource:
    url: "@spring.datasource.url@"
    username: "@spring.datasource.username@"
    password: "@spring.datasource.password@"
    driver-class-name: "@spring.datasource.driver-class-name@"

database:
  type: "@database.type@"